version: '3.8'

networks:
  network-grupo3:
    driver: bridge

services:
  redis:
    image: "redis/redis-stack:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - network-grupo3

  rabbitmq:
    image: "rabbitmq:management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network-grupo3

  webserver:
    image: josuegaticaodato/webserver
    container_name: webserver
    ports:
      - "5000:5000"
    depends_on:
      - joiner
      - spliter
    networks:
      - network-grupo3

  joiner:
    image: josuegaticaodato/joiner
    container_name: joiner
    ports:
      - "5002:5002"
    depends_on:
      - spliter
    networks:
      - network-grupo3

  spliter:
    image: josuegaticaodato/spliter
    container_name: spliter
    ports:
      - "5001:5001"
    networks:
      - network-grupo3