version: '3.8'

networks:
  network-grupo3:
    driver: bridge

services:
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      - network-grupo3

  rabbitmq:
    image: "rabbitmq:management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network-grupo3
    volumes:
      - /rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  webserver:
    image: josuegaticaodato/webserver-h2
    container_name: webserver
    ports:
      - "5000:5000"
    depends_on:
      - joiner
      - spliter
    networks:
      - network-grupo3

  joiner:
    image: josuegaticaodato/joiner
    container_name: joiner
    ports:
      - "5002:5002"
    depends_on:
      - spliter
    networks:
      - network-grupo3
    environment:
      PASSWORD: grupo3

  spliter:
    image: josuegaticaodato/spliter-h2
    container_name: spliter
    ports:
      - "5001:5001"
    networks:
      - network-grupo3
    environment:
      PASSWORD: grupo3